version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerenSingleISGH2909Project
  gitServerName: src_shared_GithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: AddPublicService
  version: "6.0"
  gitServerName: srcCtrl_shared_gitlab_Arti
  gitUrl: https://gitlab.com/ArtiKhareGitlab
  gitUsername: ArtiKhareGitlab
  gitBranch: lowerversion
services:
- serviceName: project.serensingleisgh2909.integrations:gitlabfs
  packages:
  - name: SerenSingleISGH2909Project
    version: "1.0"
  - name: AddPublicService
    version: "6.0"
- serviceName: AddPublicService:addpublicService
  packages:
  - name: AddPublicService
    version: "6.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.1211
